spring:
    application:
        name: TechGalaxy

    datasource:
        url: jdbc:sqlserver://localhost:1433;databaseName=TechGalaxy;encrypt=false
        username: sa
        password: sapassword
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.SQLServerDialect

    
    mail:
        host: smtp.gmail.com
        port: 587
        username: congtyviethan1234@gmail.com
        password: wvbnfkobkcizvlxi
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

